# docker-compose file syntax version
version: '3.5'

# volumes
volumes:
  redis_data: {}
  pg_data: {}

# services
services:
  # Redis
  redis:
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data

  # Postgres service
  # db:
  #   image: ${DB_IMAGE:-postgres:13.3}
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
  #     POSTGRES_USER: ${DB_USERNAME:-postgres}
  #     POSTGRES_DB: ${DB_DATABASE:-homestead}
  #   ports:
  #     - ${DB_PORT:-5432}:5432
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   environment:
  #     - ADMINER_DESIGN=flat
  #   ports:
  #     - ${ADMINER_PORT:-8080}:8080
